import Head from "next/head";
import styles from "styles/Home.module.css";
import React from "react";
import { GetServerSideProps } from "next";
import { getSession } from "next-auth/client";
import { routes } from "lib/nav/routes";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome :)</h1>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });
  if (!session) {
    return {
      redirect: {
        destination: routes.login,
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};

export default Home;
