import Head from "next/head";
import styles from "styles/Home.module.css";
import React from "react";
import { GetServerSideProps } from "next";
import { getSession } from "next-auth/client";
import { PATHS } from "lib/nav/routes";
import { Canvas } from "react-three-fiber";
import Box from "components/Three/Box/Box";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas>
        {/* <ambientLight />
        <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
        <pointLight position={[-10, -10, -10]} /> */}
        <Box position={[0, 0, 0]} />
      </Canvas>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });
  if (!session) {
    return {
      redirect: {
        destination: PATHS.LOGIN.path,
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};

export default Home;
