const BAD_RERQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_STATUS_CODE = 401;
const UNPROCESSABLE_ENTITY_STATUS_CODE = 422;

const INTERNAL_SERVER_ERROR = 500;

const OK_SUCCESS_STATUS_CODE = 200;
const CREATED_SUCCESS_STATUS_CODE = 201;

export {
  BAD_RERQUEST_STATUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  UNPROCESSABLE_ENTITY_STATUS_CODE,
  INTERNAL_SERVER_ERROR,
  OK_SUCCESS_STATUS_CODE,
  CREATED_SUCCESS_STATUS_CODE,
};
